# PHP
# Test and package your PHP application.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  phpVersion: 7.2

steps:

- script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
  displayName: 'Download the latest Unified Agent'

- script: 'java -jar wss-unified-agent.jar -detect -apiKey cec9e87439cc4a408732aef6990390dfcc7c4da41c6c43cb929ce1bfd0da6186 -product Cases -project 69863 -loglevel debug'
  displayName: 'Run Unified Agent Scan'